export const FETCH_DATA_SMALL = 'FETCH_DATA_SMALL';
export const FETCH_DATA_BIG = 'FETCH_DATA_BIG';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_DATA_STARTED = 'FETCH_DATA_STARTED'
export const DID_BIG_TABLE_ENTER = 'DID_BIG_TABLE_ENTER';
export const DID_SMALL_TABLE_ENTER = 'DID_SMALL_TABLE_ENTER'

