export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_DATA_STARTED = 'FETCH_DATA_STARTED';
export const TABLE_COLUMN_SORTED = 'TABLE_COLUMN_SORTED';
export const TABLE_PAGE_CHANGED = 'TABLE_PAGE_CHANGED';
export const TABLE_ADD_NEW_COLUMN = 'TABLE_ADD_NEW_COLUMN';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const FILTER_TABLE_CONTENT = 'FILTER_TABLE_CONTENT ';
export const TABLE_DATA_CLICKED = 'TABLE_DATA_CLICKED';


